### ISSUE TITLE
Dependency to doctrine/doctrine-bundle

### ISSUE THREAD

**Issue by fcool** [DamienHarper/auditor#1]
Is there a specific reason to depend on `doctrine/doctrine-bundle`.

I am currently investigating the possibility to use it with a different framework, using components from symfony is completly fine, but doctrine-bundle pulls in the dependency-injection and with it more or less the complete framework.

From a code perspective at least none of the classes of `Doctrine\Bundle` is used, so it would be great, if this would not be runtime dependency (ok for dev-dependencies, if it is needed for tests).

Other opinions? I was very lucky to have found a component not beeing already a bundle itself. ;)

**Comment by fcool** [comment]
Never mind... I guess this library is work in progress, now that I studied the source code. If so, just feel free to close this PR - if you need someone who tries an integration different from symfony feel free to contact me

**Comment by DamienHarper** [comment]
@fcool Sorry for the delay, `auditor` relies on providers to provide auditing services (listen to actions/operations to be audited and translate them into audit events) and storage services (persist audit events). 
As of now, and mainly because `auditor` is born from the split of `DoctrineAuditBundle` into a core library and a symfony bundle, `auditor` comes with a default provider for `Doctrine` named `DoctrineProvider`. 

Though, this default provider may not be bundled by default with `auditor` in the future.

**Comment by fcool** [comment]
Hi @DamienHarper 

for me, it would be super cool, if this default provider would move to the bundle. Because pulling in the DI-Container from Symfony in any other framework does not work that well. While components are perfectly fine

**Comment by DamienHarper** [comment]
@fcool Could you please elaborate, I'm not sure to fully understand what you mean.

**Comment by fcool** [comment]
`auditor` depends on `doctrine-bundle`. The doctrine-bundle is dependent on the `symfony/dependency-injection` and on `symfony/framework-bundle`, and on `symfony/framework-bundle`.

So trying to use the "base" library will still force you to use a complete symfony framework. Which it would not, if the base library would not depend on `doctrine-bundle` but on `doctrine-orm`, for example.

More clear? If not, please try to get more specfic. And I will love to keep answering. ;)

**Comment by DamienHarper** [comment]
@fcool oh I think I understood, the dependency to `doctrine/doctrine-bundle`was a leftover from the split of `DoctrineAuditBundle`. It is removed from `auditor` now in `master`

**Comment by fcool** [comment]
I'll try  a new integration again, then. And if there are still issues, I will open new ones. Thanks so much.
