### ISSUE TITLE
Page https://damienharper.github.io/docs/auditor/upgrading.html#upgrading-from-a-previous-version throws 404

### ISSUE THREAD

**Issue by parijke** [DamienHarper/auditor#10]
Document path isn't correct
https://damienharper.github.io/docs/auditor/upgrading.html#upgrading-from-a-previous-version

should be this I think
https://damienharper.github.io/auditor-docs/docs/auditor/upgrading.html#upgrading-from-a-previous-version

**Comment by DamienHarper** [comment]
@parijke You're right, linked are broken right now, I'm gonna fix them asap

**Comment by parijke** [comment]
Great! I found them anyway and goint to try the upgrade today

**Comment by DamienHarper** [comment]
Great, tell me if you need some help ;)

**Comment by parijke** [comment]
Here it comes:
Install issue
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for damienharper/auditor-bundle ^4.0 -> satisfiable by damienharper/auditor-bundle[4.0.0].
    - damienharper/auditor-bundle 4.0.0 requires damienharper/auditor dev-master -> satisfiable by damienharper/auditor[dev-master] but these conflict with your requirements or minimum-stability.
```

**Comment by DamienHarper** [comment]
@parijke good catch, your PR has been merged

**Comment by DamienHarper** [comment]
Broken links should be fixed now.

**Comment by parijke** [comment]
I will try them Damien, thx. I upgraded and all went well (doing it with the current 4.0.0 which still requires dev-master for the auditor. So I am rolling back for now and stash the changes to re-apply them when the release contains the new composer.json.

Thanks it works fine after the upgrade!

**Comment by DamienHarper** [comment]
I will push `4.0.1` including your PR later today

**Comment by DamienHarper** [comment]
@parijke `4.0.1` is available
