### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by SanderVerkuil** [DamienHarper/auditor#102]
On the 19th of April, two bugs have been fixed (#99 and #97). Currently, our project uses the `dev-master` version of the project, because no new version has been released. When will the new version including these bug fixes be released?

And should a new version be released for the DamienHarper/auditor-bundle as well, with the updated dependency to 2.0.3?

**Comment by DamienHarper** [comment]
@SanderVerkuil `2.0.3` is out
