### ISSUE TITLE
global enable disable moved, maybe thats okay

### ISSUE THREAD

**Issue by webmasterMeyers** [DamienHarper/auditor#12]
As always, thanks for your work on this bundle.  I wrote a PR on the old version, a "global" runtime enable/disable.

I am just updating to v4, and `DH\Auditor\Provider\Doctrine\Configuration::disable()` no longer exists.  I did a bit of digging around, and my code is still there, I just have to do `DH\Auditor\Configuration::disable()`

This is not a huge deal, and maybe that makes more sense with the new split setup.  But, should there maybe be a "shortcut" in `DH\Auditor\Provider\Doctrine\Configuration` to the `DH\Auditor\Configuration` enable and disable?

What are your thoughts?

**Comment by DamienHarper** [comment]
Hi @webmasterMeyers! 
The global enable/disable feature, as its name suggests, does let you enable and disable auditing globally. Also, `auditor` lets you use several providers simultaneously (a provider provides auditing and/or storage services to `auditor`). 

So, it makes sense that the enable/disable toggle is tied to `auditor` itself (through its `Configuration` object) and not to every provider available (even if there's only one at the moment).

**Comment by webmasterMeyers** [comment]
Sounds good to me!
