### ISSUE TITLE
Error on upgrading symfony 6.2

### ISSUE THREAD

**Issue by vindert** [DamienHarper/auditor#141]
When I upgrade to symfony 6.2 I get this error:

!!  Error {#613
 !!    #message: "Call to a member function addEventSubscriber() on null"
 !!    #code: 0
 !!    #file: "./vendor/damienharper/auditor/src/Provider/Doctrine/DoctrineProvider.php"
 !!    #line: 51
 !!    trace: {
 !!      ./vendor/damienharper/auditor/src/Provider/Doctrine/DoctrineProvider.php:51 { …}

**Comment by dmitryuk** [comment]
I also updated to SF 6.2 without issues.
```
$evm = $entityManager->getEventManager();
        // Register subscribers
        $evm->addEventSubscriber(new TableSchemaSubscriber($this));
```

Looks like `getEventManager` returns null, but it must be set. Can you debug why it is empty?

**Comment by DamienHarper** [comment]
@vindert Thanks for the report, though I still can't reproduce it. I upgraded several projects to Symfony 6.2 and didn't encounter that issue. What version of `auditor` are you using?

**Comment by frostieDE** [comment]
I can confirm this error for my project, but somehow it only gets triggered when running unit tests...

**Comment by frostieDE** [comment]
Don't know if it helps, but this is my stacktrace:

```
Error : Call to a member function addEventSubscriber() on null
 D:\Dev\Web\schulit\icc\vendor\damienharper\auditor\src\Provider\Doctrine\DoctrineProvider.php:51
 D:\Dev\Web\schulit\icc\var\cache\test\ContainerGqhcgRw\App_KernelTestDebugContainer.php:2216
 D:\Dev\Web\schulit\icc\var\cache\test\ContainerGqhcgRw\getCreateSchemaListenerService.php:22
 D:\Dev\Web\schulit\icc\var\cache\test\ContainerGqhcgRw\App_KernelTestDebugContainer.php:811
 D:\Dev\Web\schulit\icc\vendor\symfony\dependency-injection\Container.php:381
 D:\Dev\Web\schulit\icc\vendor\symfony\dependency-injection\Argument\ServiceLocator.php:40
 D:\Dev\Web\schulit\icc\vendor\symfony\doctrine-bridge\ContainerAwareEventManager.php:191
 D:\Dev\Web\schulit\icc\vendor\symfony\doctrine-bridge\ContainerAwareEventManager.php:114
 D:\Dev\Web\schulit\icc\vendor\dama\doctrine-test-bundle\src\DAMA\DoctrineTestBundle\Doctrine\DBAL\StaticConnectionFactory.php:44
 D:\Dev\Web\schulit\icc\var\cache\test\ContainerGqhcgRw\App_KernelTestDebugContainer.php:945
 D:\Dev\Web\schulit\icc\var\cache\test\ContainerGqhcgRw\App_KernelTestDebugContainer.php:965
 D:\Dev\Web\schulit\icc\vendor\symfony\var-exporter\Internal\LazyObjectState.php:95
 D:\Dev\Web\schulit\icc\vendor\symfony\var-exporter\LazyGhostTrait.php:174
 D:\Dev\Web\schulit\icc\vendor\doctrine\orm\lib\Doctrine\ORM\EntityManager.php:876
 D:\Dev\Web\schulit\icc\vendor\doctrine\orm\lib\Doctrine\ORM\EntityManager.php:663
 D:\Dev\Web\schulit\icc\tests\Entity\DocumentCategoryTest.php:35
```

**Comment by vindert** [comment]
I haven't been able to debug anything. I'm not sure where to took for what is null.

Maybe it is related to these two issues:
https://github.com/DamienHarper/auditor/issues/36
https://github.com/DamienHarper/auditor-bundle/issues/228

On my my sf 6.1 project I still need to use this fix for AuditorBundle to work, and save the changes
https://github.com/DamienHarper/auditor-bundle/issues/228#issuecomment-752381976

@DamienHarper Maybe I can give you acces to my repository so you can run it your self?

**Comment by Marmelatze** [comment]
Had the problem occuring in tests. The EventManager is null and the EntityManager is an ghost instance. I was able to fix it in the tests by making the EntityManager not lazy:

```yaml
# services_test.yaml
  doctrine.orm.entity_manager.abstract:
    class: '%doctrine.orm.entity_manager.class%'
    lazy: false
    abstract: true
```

**Comment by vindert** [comment]
For me the issue also occurs when not in test env. 
With the config from @Marmelatze in services.yaml I can update to 6.2.
Also the workaround as suggested in the link I posted earlier: https://github.com/DamienHarper/auditor-bundle/issues/228#issuecomment-752381976 is not needed anymore.

**Comment by dmitryuk** [comment]
@Marmelatze Do you use `dama\doctrine-test-bundle` ?

**Comment by Marmelatze** [comment]
@dmitryuk: yes, I was using version 6.7.5 now I'm using 7.1.1 and the service overwrite is no longer necessary.

**Comment by dmitryuk** [comment]
@vindert can you update `dama\doctrine-test-bundle` up to `7.1.1` and recheck the issue without extra config?

**Comment by vindert** [comment]
I'm already using that version, and still have the error. And since that bundle is only used in test env, the chances were small this would fix it for me, since in my case it is not only happening test env.. But it did start me thinking of other conflicting bundles and tried disable other bundles. The error occurs when using "bin/console cache:clear". And when I comment out the bundle [DoctrineEnumBundle](https://github.com/fre5h/DoctrineEnumBundle) and run the command again I don't get the error.  I searched the issues for that bundle and Ifound this [issue](https://github.com/fre5h/DoctrineEnumBundle/issues/187). Maybe something similar is happening here with this bundle? My php/symfony knowledge is not big enough to dig deeper.

**Comment by dmitryuk** [comment]
@vindert I will check the bundle and back to you..

**Comment by dmitryuk** [comment]
@vindert can you send actual error stack trace? Your [comment](https://github.com/DamienHarper/auditor/issues/141#issuecomment-1359807773) has old version of `doctrine-test-bundle`

**Comment by dmitryuk** [comment]
I tried to install `DoctrineEnumBundle`, `doctrineTestBundle` without issues. Still need more details

**Comment by vindert** [comment]
This is the error I get when I trying to upgrade:

```
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 255
!!  Error {#785
!!    #message: "Call to a member function addEventSubscriber() on null"
!!    #code: 0
!!    #file: "./vendor/damienharper/auditor/src/Provider/Doctrine/DoctrineProvider.php"
!!    #line: 51
!!    trace: {
!!      ./vendor/damienharper/auditor/src/Provider/Doctrine/DoctrineProvider.php:51 { …}
!!      ./var/cache/dev/ContainerQ0agfyx/App_KernelDevDebugContainer.php:1828 {
!!        ContainerQ0agfyx\App_KernelDevDebugContainer->getDoctrineProviderService()
!!        › $instance->registerStorageService(new \DH\Auditor\Provider\Doctrine\Service\StorageService('dh_auditor.provider.doctrine.storage_services.doctrine.orm.default_entity_manager', $a));
!!        › $instance->registerAuditingService(new \DH\Auditor\Provider\Doctrine\Service\AuditingService('dh_auditor.provider.doctrine.auditing_services.doctrine.orm.default_entity_manager', $a));
!!        › 
!!      }
!!      ./var/cache/dev/ContainerQ0agfyx/getDoctrineSubscriberService.php:24 { …}
!!      ./var/cache/dev/ContainerQ0agfyx/App_KernelDevDebugContainer.php:741 { …}
!!      ./vendor/symfony/dependency-injection/Container.php:381 { …}
!!      ./vendor/symfony/dependency-injection/Argument/ServiceLocator.php:40 { …}
!!      ./vendor/symfony/doctrine-bridge/ContainerAwareEventManager.php:191 { …}
!!      ./vendor/symfony/doctrine-bridge/ContainerAwareEventManager.php:105 { …}
!!      ./vendor/doctrine/dbal/src/Connection.php:384 { …}
!!      ./vendor/doctrine/dbal/src/Connection.php:446 { …}
!!      ./vendor/doctrine/dbal/src/Connection.php:408 { …}
!!      ./vendor/doctrine/dbal/src/Connection.php:316 { …}
!!      ./vendor/doctrine/doctrine-bundle/ConnectionFactory.php:131 { …}
!!      ./vendor/doctrine/doctrine-bundle/ConnectionFactory.php:109 { …}
!!      ./var/cache/dev/ContainerQ0agfyx/App_KernelDevDebugContainer.php:974 { …}
!!      ./var/cache/dev/ContainerQ0agfyx/App_KernelDevDebugContainer.php:1125 { …}
!!      ./vendor/symfony/var-exporter/Internal/LazyObjectState.php:95 { …}
!!      ./vendor/symfony/var-exporter/LazyGhostTrait.php:175 { …}
!!      ./vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php:866 { …}
!!      ./vendor/symfony/doctrine-bridge/CacheWarmer/ProxyCacheWarmer.php:50 { …}
!!      ./vendor/symfony/http-kernel/CacheWarmer/CacheWarmerAggregate.php:96 { …}
!!      ./vendor/symfony/http-kernel/Kernel.php:526 { …}
!!      ./vendor/symfony/http-kernel/Kernel.php:709 { …}
!!      ./vendor/symfony/http-kernel/Kernel.php:122 { …}
!!      ./vendor/symfony/framework-bundle/Console/Application.php:148 { …}
!!      ./vendor/symfony/framework-bundle/Console/Application.php:69 { …}
!!      ./vendor/symfony/console/Application.php:168 { …}
!!      ./vendor/symfony/runtime/Runner/Symfony/ConsoleApplicationRunner.php:54 { …}
!!      ./vendor/autoload_runtime.php:29 { …}
!!      ./bin/console:11 { …}
!!    }
!!  }
!!  2023-02-08T20:15:10+01:00 [critical] Uncaught Error: Call to a member function addEventSubscriber() on null
!!  
```
If it helps I can also give you access to my git repository @dmitryuk ?

**Comment by vindert** [comment]
I have found out that the issue  is only happens when using the dev environment (APP_DEBUG=1)

**Comment by tomme87** [comment]
Had the same issue, solved it by upgrading `dama/doctrine-test-bundle` to v7

**Comment by mkldevops** [comment]
```yaml
# config/packages/dh_auditor.yaml
when@dev: &when_dev
    dh_auditor:
        providers:
            doctrine:
                table_suffix: '_audit'
                ignored_columns:
                    - 'createdAt'
                    - 'updatedAt'
                viewer: true

when@prod: *when_dev
```
```yaml
# config/routes/dh_auditor.yaml

when@dev: &when_dev
    dh_auditor:
        resource: "@DHAuditorBundle/Controller/"
        type: auditor

when@prod: *when_dev
```php
# config/bundles.php
[
    ....
    DH\AuditorBundle\DHAuditorBundle::class => ['dev' => true, 'prod' => true],
]
```

**Comment by vindert** [comment]
I have found out that this bug only occurs with an ms-sql database server. 
It doesn't  happen with a mariadb or mysql server

**Comment by vindert** [comment]
No, I'm not sure how I got it working, but this issue no longer happens
