### ISSUE TITLE
Breaking Change in PR#137

### ISSUE THREAD

**Issue by Arconian** [DamienHarper/auditor#142]
| Q                    | A
| ---------------------| -----------------------
| `auditor` version    | 2.4.0
| `doctrine/orm` version    | 2.7.5
| PHP version          | 7.4
| Database             | MySQL

#### Summary
#137 broke the compatibility with `doctrine/orm` <2.9 . Method [getMetadataCache()](https://github.com/DamienHarper/auditor/commit/1f8b06285b6d47463f495a1d345dec7d47b1d20d#diff-66f22bac67db554b3a856fac21a4ef90294c5874c348ab7f3b3947b5eba00ffeR233) has only been introduced in [doctrine/orm 2.9](https://github.com/doctrine/orm/blob/2.9.x/lib/Doctrine/ORM/Configuration.php).

#### Current behaviour

When using any doctrine related code of your application, you get
`Attempted to call an undefined method named "getMetadataCache" of class "Doctrine\ORM\Configuration".`

#### How to reproduce

Install auditor 2.4.0 with doctrine/orm 2.7.5
Use auditor

#### Expected behaviour

No errors are thrown.

**Comment by DamienHarper** [comment]
@Arconian thanks for the report, this is fixed in `2.4.1` release (thanks to @dmitryuk)
