### ISSUE TITLE
2.4.4 broke enum compatibility

### ISSUE THREAD

**Issue by nesl247** [DamienHarper/auditor#153]
| Q                    | A
| ---------------------| -----------------------
| `auditor` version    | 2.4.4
| PHP version          | 8.1.13
| Database             | PostgreSQL 13

#### Summary

2.4.4 broke diffs when the `new` is an enum. I was able to revert to 2.4.3 and the issue went away.

#### Current behavior

```mb_convert_encoding(): Object is not supported```
![CleanShot 2023-01-24 at 15 43 36](https://user-images.githubusercontent.com/1037526/214406777-2ac5f8da-0ebd-44d6-8527-db40fd378b82.png)

#### How to reproduce

Create an entity with an string backed enum property, and try to persist a change.

#### Expected behavior

The diff is generated without error

**Comment by DamienHarper** [comment]
Fixed thanks to @martijnboers
