### ISSUE TITLE
Warning: mb_convert_encoding(): Object is not supported

### ISSUE THREAD

**Issue by koencaerels** [DamienHarper/auditor#155]
mysql 5.7
php 8.1
symfony 6.2.6
doctrine bundle 2.7
damienharper/auditor-bundle 5.2.1
damienharper/auditor 2.4.4 

https://github.com/DamienHarper/auditor/commit/1779e1e1c73930f22a418de04b5ec1d78406e35f

src/Provider/Doctrine/Auditing/Transaction/TransactionProcessor.php

Line 220 > `'diffs' => json_encode(mb_convert_encoding($data['diff'], 'UTF-8', 'UTF-8'), JSON_THROW_ON_ERROR),`

Throws this error: "Warning: mb_convert_encoding(): Object is not supported"

This happens when you have a database table with a json (type) field with this kind of information in it [{id:1, ...},{id:2, ...}].

**Comment by martijnboers** [comment]
Sadly by how audit-bundle is requiring auditor with a `^` I cannot install this wonderful bundle as it crashes my fixtures.

**Comment by nesl247** [comment]
Same error as #153 I believe.

**Comment by DamienHarper** [comment]
Fixed thanks to @martijnboers
