### ISSUE TITLE
Auditing outside of Doctrine Entities

### ISSUE THREAD

**Issue by zaiddabaeen** [DamienHarper/auditor#16]
Is there a way for us to audit log a database operation that happened through SQL? Maybe writing our own provider? Are there any examples of this?

Thanks!

**Comment by DamienHarper** [comment]
@zaiddabaeen I'm sorry but this is not possible. 

`auditor` relies on Doctrine events and on UnitOfWork to get the changeset (data which changed) thanks to the `DoctrineProvider`.

Direct SQL can be achieved through Doctrine DBAL or through PDO but both of them do not fire any useful event (if any) and both of them do not provide any way to get what's been updated/created/deleted.
