### ISSUE TITLE
Wrong migration when using Postgres

### ISSUE THREAD

**Issue by OskarStark** [DamienHarper/auditor#180]
| Q                    | A
| ---------------------| -----------------------
| `auditor` version    | 2.4.7
| PHP version          | 8.2
| Database             | PostgreSQL

#### Summary

Generated migration does not work

#### Current behavior

When I generate a diff, using `doctrine/migrations`, I get the following migration:

```php
final class Version20231010102853 extends AbstractMigration
{
    public function up(Schema $schema): void
    {
        $this->addSql('ALTER TABLE addresses_audit ALTER diffs TYPE JSON USING diffs::JSON');
    }
}
```

resulting in:
![CleanShot 2023-10-10 at 13 40 49@2x](https://github.com/DamienHarper/auditor/assets/995707/53208dfc-404f-4aea-98c5-df56bef2d8e8)

The correct migration would be:
```diff
final class Version20231010102853 extends AbstractMigration
{
    public function up(Schema $schema): void
    {
-        $this->addSql('ALTER TABLE addresses_audit ALTER diffs TYPE JSON');            
+        $this->addSql('ALTER TABLE addresses_audit ALTER diffs TYPE JSON USING diffs::JSON');
    }
}
```

Otherwiese, Postgres cannot convert the JSON from a TEXT field to a native JSON 🤷 

cc @mvhirsch

**Comment by DamienHarper** [comment]
Thanks for the report @OskarStark.

**Comment by DamienHarper** [comment]
@OskarStark Sorry for this very late reply. Well it looks like it's a Doctrine issue as `auditor` does rely on Doctrine to get most schema transformation/alter queries.
Do you still face that issue?

**Comment by OskarStark** [comment]
I fixed it once manually

**Comment by DamienHarper** [comment]
@OskarStark I close this issue for now as it seems to be Doctrine related. Feel free to reopen if needed.
