### ISSUE TITLE
Multiple Logs Updates with Decimal values

### ISSUE THREAD

**Issue by desousalopes** [DamienHarper/auditor#188]
Good afternoon.

I'm having a problem with fields with decimal places, for example:
`    /**
     * @ORM\Column(type="decimal", scale=4, precision=14, nullable=true)
     */
    protected $originalAmount = null;
`

When I change a record, the decimal places change, but in the database they are stored with the correct decimal places.

`{"value":{"new":10.11,"old":"10.1100"},"modifiedDate":{"new":"2023-11-28 17:58:12","old":"2023-11-28 17:57:32"},"taxedValue":{"new":10.11,"old":"10.1100"},"untaxedValue":{"new":0,"old":"0.0000"}}`

I was wondering if there was any way of overcoming this decimal point issue, because it doesn't make much sense to have a log with the difference from 0.00 to 0.0000.

Thank you.

**Comment by pedrocasado** [comment]
https://github.com/DamienHarper/auditor-bundle/issues/299#issuecomment-1067139317
