### ISSUE TITLE
ORM 3

### ISSUE THREAD

**Issue by FluffyDiscord** [DamienHarper/auditor#194]
Doctrine ORM 3 was released recently and this lovely package is in need of updating

**Comment by pedrocasado** [comment]
Same here. That would be helpful.

**Comment by DamienHarper** [comment]
[3.0.0 is released](https://github.com/DamienHarper/auditor/releases/tag/3.0.0)

**Comment by FluffyDiscord** [comment]
thank you for being awesome!
