### ISSUE TITLE
Support for Binary formats. (Ramsey: uuid_binary/uuid_binary_ordered_time)

### ISSUE THREAD

**Issue by NikoGrano** [DamienHarper/auditor#2]
## Context
- Using Symfony 5.x
- Using PHP 7.4
- Using Ramsey UuidBundle
- Added following Types and Mapping Types:
```yaml
        types:
          uuid_binary: Ramsey\Uuid\Doctrine\UuidBinaryType
          uuid_binary_ordered_time: Ramsey\Uuid\Doctrine\UuidBinaryOrderedTimeType
        mapping_types:
          uuid_binary: binary
          uuid_binary_ordered_time: binary
```

- I have following entity:

```php
/**
 * @ORM\Entity
 * @ORM\Table(...)
 * @Auditable()
 */
class Xxx implements Yyy
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="CUSTOM")
     * @ORM\CustomIdGenerator(class="Ramsey\Uuid\Doctrine\UuidOrderedTimeGenerator")
     * @ORM\Column(type="uuid_binary_ordered_time", unique=true)
     * @Ignore()
     */
    private Uuid $id;

    /**
     * @ORM\Column(...)
     */
    public string $yyy;
}
```

## Error

Audit will fail to SQL error on insert. Example of error is following:
```
An exception occurred while executing 'INSERT INTO namespace_Xxx_audit (type, object_id, discriminator, transaction_hash, diffs, blame_id, blame_user, blame_user_fqdn, blame_user_firewall, ip, created_at) VALUES (:type, :object_id, :discriminator, :transaction_hash, :diffs, :blame_id, :blame_user, :blame_user_fqdn, :blame_user_firewall, :ip, :created_at)' with params ["insert", "\x11\xea\xb4\x47\xd5\x35\xc1\xd2\x99\x2f\x02\x42\xac\x1e\x00\x09", null, "16e29081336395cbe0f08971bb4f51b584dd94a0", "{\"firstName\":{\"old\":null,\"new\":\"F\"},\"lastName\":{\"old\":null,\"new\":\"L\"}}", null, null, null, "login", "172.30.0.1", "2020-06-22 06:18:40"]:

SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\xEA\xB4G\xD55\xC1...' for column `database`.`namespace_Xxx_audit`.`object_id` at row 1
```

## Problem

The problem is caused due value is expected to be string value when in the DB, but when code runs `convertToDatabaseValue()` [here](https://github.com/DamienHarper/auditor/blob/75ad5a1312524181bb291ccc2ddd04544ec8da6f/src/Provider/Doctrine/Auditing/Transaction/AuditTrait.php#L80), it will convert it from string to binary which causes this error.

## Solution

To solve this you need to be able specify which types are ran with `$type->convertToPHPValue($value, $platform);` instead of `$type->convertToDatabaseValue($value, $platform);`. Another solutions is to run `(string)` or `__toString()` cast on this  value.

I am not honestly sure how this can be achived without hacky solutions, but I was thinking as you are refactoring everything for v4, this could be implemented in same rewrite.

### Context to Problem/Solution
https://github.com/DamienHarper/auditor/blob/75ad5a1312524181bb291ccc2ddd04544ec8da6f/src/Provider/Doctrine/Auditing/Transaction/AuditTrait.php#L55-L84

#### Extra

I dont want push you, but I am waiting v4 to finish stable state and this feature to be published before I add this library to my new project. Thank you for your awesome work. :1st_place_medal:

**Comment by DamienHarper** [comment]
@NikoGrano Thanks for your feedback and (very) sorry for that late reply. I think the issue you describe has been fixed in a recent release. I close the issue, feel free to reopen if needed.
