### ISSUE TITLE
Multifilters broken because of doctrine behavior

### ISSUE THREAD

**Issue by Maksclub** [DamienHarper/auditor#22]
| Q                    | A
| ---------------------| -----------------------
| `auditor` version    | x.y.z
| PHP version          | 7.1
| Database             | MySQL / PostgreSQL / SQLite / Other

#### Summary

Hello! Critical error founded

The error is reproduced in this case:
```
$query->addFilter('object_id', 1);
$query->addFilter('object_id', 34);
```
This code will generate an error:
`An exception occurred while executing 'SELECT * FROM contact_audit at WHERE object_id IN (?) ORDER BY created_at DESC, id DESC LIMIT 50' with params [[1,34]]
Notice: Array to string conversion`

**Cause of error:** 
`The parameter list support only works with Doctrine\DBAL\Connection::executeQuery() and Doctrine\DBAL\Connection::executeUpdate(), NOT with the binding methods of a prepared statement.`

Source: https://www.doctrine-project.org/projects/doctrine-dbal/en/2.9/reference/data-retrieval-and-manipulation.html#list-of-parameters-conversion

_Sorry for my rude and bad english_

**Comment by Maksclub** [comment]
Pull Request: https://github.com/DamienHarper/auditor/pull/21

**Comment by DamienHarper** [comment]
Thanks @Maksclub for the report and the PR. It's merged now
