### ISSUE TITLE
reader->createQuery->addFilter by array of object_ids

### ISSUE THREAD

**Issue by Alexandr-Du** [DamienHarper/auditor#29]
Hi! How can I make a query with a filter by array of object_ids?

**Comment by DamienHarper** [comment]
@Alexandr-Du You should now be able to achieve what you want by using for example
```php
// ...
$objectIds = [1, 2, 3];
$query->addFilter(new SimpleFilter(Query::OBJECT_ID, $objectIds));
// ...
```

**Note**: this is available on `master` only until I release `1.2.0`. Feel free to reopen this issue if needed.
