### ISSUE TITLE
Auditor use specific field of related Table instead of ID for log

### ISSUE THREAD

**Issue by gomez77** [DamienHarper/auditor#32]
Hi,
first thanks for this flexible bundle.

I developed an own "audit service" but this isn't flexible and professional then yours.
But I used a specific filed to log on related fields instead of the ID

Example:
Your approach: status	old: App\Entity\Status#4	 new: App\Entity\Status#1
My approach: status old: planing new: operation

The record #4 with the field name= planing
The record #1 with the field name = operation

The advantage is, it is traceable in the AuditLog to which exact value it was changed.

If somebody changed the field of the related table it isn't exact traceable which field was used with your approach.
 
Is this possible?

Thanks

**Comment by DamienHarper** [comment]
@gomez77 Sorry for this late reply, did you try to add a `__toString()` method to your entities? It should do the trick.

**Comment by gomez77** [comment]
Hi,
thanks for this very useful hint! It is working! You can close this issue.

I'm happy to decide to use your package!
