### ISSUE TITLE
Fail to audit Entity with composite primary key

### ISSUE THREAD

**Issue by gam6itko** [DamienHarper/auditor#33]
| Q                    | A
| ---------------------| -----------------------
| `auditor` version    | 1.2.0
| PHP version          | any
| Database             | any

#### Summary

Throws `MappingException` when tries to record audit log for Entity which has complex primary keys

#### How to reproduce

I've made demo project for this bug. https://github.com/gam6itko/auditor-multi-id-bug

Look at `MultiIdTest`

**Comment by DamienHarper** [comment]
@gam6itko Thanks for the report and demo project, will have a look at it asap

**Comment by DamienHarper** [comment]
@gam6itko I'm sorry but I don't plan to add support for composite primary keys as it would require a lot of internal changes and would imply backward compatibility troubles. 
This has already been requested/discussed [here](https://github.com/DamienHarper/auditor-bundle/issues/57#issuecomment-814402261)

**Comment by DamienHarper** [comment]
A simple solution is to add an autoincremented id (so single column primary key) to such entities/tables.
In addition, you can add a unique composite index spanning on relevant columns to keep being duplicate safe.

**Comment by gam6itko** [comment]
> @gam6itko I'm sorry but I don't plan to add support for composite primary keys as it would require a lot of internal changes and would imply backward compatibility troubles.

@DamienHarper can you please add note about is in documentation? In "Known issues" section or something

**Comment by DamienHarper** [comment]
Sûre, I'll do 👍🏽

**Comment by DamienHarper** [comment]
I added a dedicated [note](https://damienharper.github.io/auditor-docs/docs/auditor/index.html) in the doc as suggested and throw a cleaner (more explicit) exception when such an entity is audited (available in `master` branch).
