### ISSUE TITLE
Manual entry in Audit tables

### ISSUE THREAD

**Issue by mattsdel** [DamienHarper/auditor#43]
Sometimes when you encounter a bug you must change the data with an adhoc query in the database. Is there a way to insert a line of the diff in the Audit tables after making the update on the database through a query?

If not, I supposed the solution is to use the ORM to make the updates?

Thanks.

**Comment by DamienHarper** [comment]
@mattsdel As mentioned in the doc
> `auditor` does not allow tracking changes resulting from direct DQL/SQL update or delete statements

So you're right, the only "easy" solution as of now is to take the ORM path.
