### ISSUE TITLE
Dissociating while removing offers no target

### ISSUE THREAD

**Issue by jhard** [DamienHarper/auditor#58]
I'm using auditor with the auditor-bundle for Symfony on the latest version (5.3).

I have an entity A that has a OneToMany relation to entity B with orphanRemoval=true, since B depends on A and cannot be transferred or stand on its own.
If I remove an entity B from A (e.g. via a form with a CollectionType), I get a transaction that looks somewhat like this:
```
App\Entity\A
App\Entity\A#132 (My Entity) has been dissociated by username , IP: 127.0.0.1

App\Entity\B
App\Entity\B#321 (Some Name) has been deleted by username , IP: 127.0.0.1
```

While it's easy enough to work out what has happened in this simple instance, it's a different question when it comes to larger transactions that might contain multiple different entities.
The reason is AuditTrait's `summarize()` method bailing early:
```
        // An added guard for proxies that fail to initialize.
        if (null === $pkValue) {
            return null;
        }
```
Without that guard, I'm getting this audit log entry:
```
App\Entity\A
App\Entity\A#132 (My Entity) has been dissociated from App\Entity\B# (Some Name) by username , IP: 127.0.0.1

App\Entity\B
App\Entity\B#321 (Some Name) has been deleted by username , IP: 127.0.0.1
```
Which is much better in my opinion. It lacks the ID because the EntityManager has already removed it at this stage in the Event, but it'll still have the label from __toString() and most importantly, it'll say what type of entity was dissociated from A.

Is there a better way to approach this?
I'm sure there's a reason to not summarize entities without primary keys and it probably can't simply be changed and create unexpected behavior legacy users. I haven't seen an obvious way to replace the `TransactionProcessor` with another class implementing `TransactionProcessorInterface`, have I missed it or is it currently impossible?

**Comment by DamienHarper** [comment]
@jhard thanks for the feedback. I have to have a closer look at what can be done for those cases where deletion happened earlier. No promise though.
Regarding `TransactionProcessor`, it wasn't meant to be overridden.

**Comment by skuhnow** [comment]
I seems it's already fixed/improved in the current master branch, but not in any release. Do you think you could release maybe 1.3.2 with this improvement? I want to avoid a fork and custom implementation.

**Comment by DamienHarper** [comment]
@skuhnow I plan to release a new major version 2.0.0 sometime between January and February.

**Comment by DamienHarper** [comment]
@jhard I forgot to close this issue when 2.0.0 was released.
