### ISSUE TITLE
Log the field for relations

### ISSUE THREAD

**Issue by jhard** [DamienHarper/auditor#59]
I have an entity `User` and another entity `Post` which might have an `author` and an `editor`. Both of these reference `User`.
If I associate and dissociate an author, there's no way to tell whether the User was assigned as the author or editor.

Is there a use-case where adding the affected field might lead to problems?

**Comment by DamienHarper** [comment]
@jhard thanks for this feedback, having a way to identify which field is involved in association/dissociation would be a nice addition. I'll investigate on what can be done here.
If you want to contribute a submit a PR, I'd be glad to review it though!

**Comment by DamienHarper** [comment]
@jhard `master` branch now keeps track of relationship fields/references.

**Comment by jhard** [comment]
Sorry for not getting back to you earlier. Looks good, thank you.
