### ISSUE TITLE
In master, PHP8 must use PHP8-style annotations instead of old-school /** ORM\Entity */ style

### ISSUE THREAD

**Issue by mkopinsky** [DamienHarper/auditor#76]
| Q                    | A
| ---------------------| -----------------------
| `auditor` version    | dev-master 19d5c11
| PHP version          | 8.0.13
| Database             | MariaDB

#### Summary

When #40 introduced PHP8 annotations, it still used `$this->reader->getClassAnnotation` if there weren't any Entity attributes.
```php
        if (\PHP_VERSION_ID >= 80000 && $attributes = $reflection->getAttributes(Entity::class)) {
            $annotation = $attributes[0]->newInstance();
        } else {
            $annotation = $this->reader->getClassAnnotation($reflection, Entity::class);
        }
```

In [#72](https://github.com/DamienHarper/auditor/pull/72/files#diff-e1cb1727d66518eb076a68bc9899bdb0edb1ce5346e1f89d8b4b75a5ba5aa437), this changed so that on PHP8, it will always use the `if` block rather than the `else` block.

```php
        if (\PHP_VERSION_ID >= 80000 && method_exists($reflection, 'getAttributes')) {
            $attributes = $reflection->getAttributes(Entity::class);
            $annotation = \count($attributes) > 0 ? $attributes[0]->newInstance() : null;
        } elseif (null !== $this->reader) {
            $annotation = $this->reader->getClassAnnotation($reflection, Entity::class);
        }
```

Same deal obviously with the other annotation checks for Auditable and Security

#### How to reproduce

```php
/**
 * @ORM\Entity(repositoryClass="App\Repository\InventoryRepository")
 * @Audit\Auditable
 */
class Inventory
{
  // ...
}
```
doesn't recognize the class as Auditable

If I add the PHP8-style attributes then it does recognize it
```php
#[
    ORM\Entity(repositoryClass: InventoryRepository::class),
    Audit\Auditable
]
```

#### Expected behavior

Even with PHP8, old-style annotations are still recognized

**Comment by DamienHarper** [comment]
@mkopinsky Thanks for the report, this should be fixed in `master` now

**Comment by mkopinsky** [comment]
Thanks!!
