### ISSUE TITLE
Support Doctrine DBAL 3

### ISSUE THREAD

**Issue by ad3n** [DamienHarper/auditor#80]
When using Doctrine DBAL 3.3.0 i got an error

```
"Error: Uncaught Error: Call to undefined method Doctrine\DBAL\Result::setFetchMode() in vendor/damienharper/auditor/src/Provider/Doctrine/Persistence/Reader/Query.php:72
```

**Comment by DamienHarper** [comment]
Hi @ad3n. Could you please provide your current `auditor` and `auditor-bundle` versions? 
`auditor 1.x` does not support `doctrine/dbal 3.x` but didn't prevent its installation. This has been fixed with `auditor  1.3.1`.

**Comment by ad3n** [comment]
@DamienHarper when using DBAL 3.X we install 1.3.0 version of Auditor I think

**Comment by DamienHarper** [comment]
You should upgrade to `auditor 1.3.1` and downgrade `doctrine/dbal` to a `2.x` until `auditor 2.0` is available (sometime in January or February)

**Comment by ad3n** [comment]
@DamienHarper thank you very much, it worked for me
