### ISSUE TITLE
Entries in reverse order on audit table when using transactions

### ISSUE THREAD

**Issue by samuel4x4** [DamienHarper/auditor#84]
| Q                    | A
| ---------------------| -----------------------
| `auditor` version    | 1.3.1
| PHP          | 7.4
| MySQL             | 5.7
| Symfony | 5.3

#### Summary
Given these insert and update operations:
```
$this->orm->beginTransaction();

$e1 = new Entity();
$e1->setProperty($value);
$this->orm->persist($e1);
$this->orm->flush();
$e1->setProperty($value);
$this->orm->flush();
$e1->setProperty($value);
$this->orm->flush();

$e2 = new Entity();
$e2->setProperty($value);
$this->orm->persist($e2);
$this->orm->flush();
$e2->setProperty($value);
$this->orm->flush();
$e2->setProperty($value);
$this->orm->flush();

$this->orm->commit();
```
On the audit table you'll have them in the reverse order:
```
$e2 update
$e2 update
$e2 insert
$e1 update
$e1 update
$e1 insert
```
If you don't use `beginTransaction()` and `commit()`, they are in the correct order:
```
$e1 insert
$e1 update
$e1 update
$e2 insert
$e2 update
$e2 update
```

Do you have any idea why is this and how should it be fixed?

**Comment by DamienHarper** [comment]
@samuel4x4 hum that's weird, I'll have a look at this during the weekend

**Comment by samuel4x4** [comment]
@DamienHarper thank you, I would be more than grateful

**Comment by DamienHarper** [comment]
@samuel4x4 I finally had time to attempt to fix this issue. Could you please check PR #86 ?

**Comment by samuel4x4** [comment]
@DamienHarper it's working like a charm, thanks a lot! I see it as a major fix, do you think can you release **1.3.2**? It will be really helpful ;)

**Comment by DamienHarper** [comment]
@samuel4x4 yeah, I'll back port it to 1.x branch and release it soon

**Comment by samuel4x4** [comment]
Thank you @DamienHarper

**Comment by DamienHarper** [comment]
@samuel4x4 [1.3.2 is live](https://github.com/DamienHarper/auditor/releases/tag/1.3.2)

**Comment by samuel4x4** [comment]
thank you @DamienHarper
