### ISSUE TITLE
Auditor fails to compute diff for new entities created in a transaction that depend on typed properties being used in the __toString()

### ISSUE THREAD

**Issue by SanderVerkuil** [DamienHarper/auditor#95]
| Q                    | A
| ---------------------| -----------------------
| `auditor` version    | 2.0.1
| PHP version          | 7.4.28
| Database             | MySQL

#### Summary

The auditor fails to create the audit trails for entities that are created within a transaction and have a custom `__toString()` method that depends on type hinted properties.

#### Current behavior

It currently throws an exception that a property must be initialized prior to accessing, or that `null` can't be used if the property has a default value.

<details><summary>Stack trace</summary>

```
Error {#220741
  #message: "Typed property Entity::$type must not be accessed before initialization"
  #code: 0
  #file: "./src/Entity.php"
  #line: 35
  trace: {
    ./src/Entity.php:35 {
      Entity->__toString()
      › {
      ›     return $this->type;
      › }
    }
    ./var/cache/selenium/doctrine/orm/Proxies/__CG__Entity.php:203 { …}
    ./vendor/damienharper/auditor/src/Provider/Doctrine/Auditing/Transaction/AuditTrait.php:198 { …}
    ./vendor/damienharper/auditor/src/Provider/Doctrine/Auditing/Transaction/AuditTrait.php:164 { …}
    ./vendor/damienharper/auditor/src/Provider/Doctrine/Auditing/Transaction/TransactionProcessor.php:60 { …}
    ./vendor/damienharper/auditor/src/Provider/Doctrine/Auditing/Transaction/TransactionProcessor.php:139 { …}
    ./vendor/damienharper/auditor/src/Provider/Doctrine/Auditing/Transaction/TransactionProcessor.php:38 { …}
    ./vendor/damienharper/auditor/src/Provider/Doctrine/Auditing/Transaction/TransactionManager.php:32 { …}
    ./vendor/damienharper/auditor/src/Provider/Doctrine/Auditing/Event/DoctrineSubscriber.php:43 { …}
    ./vendor/damienharper/auditor/src/Provider/Doctrine/Auditing/Logger/Logger.php:28 { …}
    ./vendor/damienharper/auditor/src/Provider/Doctrine/Auditing/Logger/LoggerChain.php:30 { …}
    ./vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:1783 { …}
    ./vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php:242 { …}
    ./vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/Executor/ORMExecutor.php:76 { …}
    ./vendor/doctrine/doctrine-fixtures-bundle/Command/LoadDataFixturesDoctrineCommand.php:158 { …}
    ./vendor/symfony/console/Command/Command.php:298 { …}
    ./vendor/symfony/console/Application.php:1033 { …}
    ./vendor/symfony/framework-bundle/Console/Application.php:96 { …}
    ./vendor/symfony/console/Application.php:299 { …}
    ./vendor/symfony/framework-bundle/Console/Application.php:82 { …}
    ./vendor/symfony/console/Application.php:171 { …}
    ./vendor/symfony/runtime/Runner/Symfony/ConsoleApplicationRunner.php:54 { …}
    ./vendor/autoload_runtime.php:35 { …}
    ./bin/console:11 { …}
  }
}
```

</details>

#### How to reproduce

I think the snippet below is the general case what happens

```php

/**
 * @Auditable()
 */
class TestEntity {
  private string $name;

  public function __construct(string $name) {
    $this->name = $name;
  }

  public function getName(): string
  {
    return $this->name;
  }

  public function __toString(): string
  {
    return $this->name;
  }
}

$em = $container->get(EntityManagerInterface::class);

$em->transactional(function($manager) {
  $test = new TestEntity('Hello');
  $manager->persist($test);
  $manager->flush();
};
```

I'll see whether I can create a PR that creates a test for this bug.

#### Expected behavior

I expected that it would not crash, and create an insert log item.

**Comment by DamienHarper** [comment]
Hi @SanderVerkuil, I've not been able to reproduce your issue so far. Could you provide a code sample that helps reproducing the issue? I tested something very similar to the code you initially provided but everything worked as intended.

```php
// Auditable entity
/**
 * @ORM\Entity
 * @ORM\Table(name="issue95")
 * @Auditable
 */
class Issue95
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    /**
     * @ORM\Column(type="string", name="type", length=50)
     */
    private string $name;

    public function __construct(string $name)
    {
        $this->name = $name;
    }

    public function __toString(): string
    {
        return $this->name;
    }

    public function getName(): string
    {
        return $this->name;
    }
}


// sample code that persist an instance of this entity
$em = $this->provider->getStorageServiceForEntity(Issue95::class)->getEntityManager();
$entity = new Issue95('issue95');
$em->persist($entity);
$em->flush();

// As expected, 1 record is added to `issue95` table as well as 1 record added to `issue95_audit` table
```

**Comment by DamienHarper** [comment]
@SanderVerkuil Looking at the provided traces, it seems that your `Entity` instance do not have the `type` property set at save time.

```
    ./src/Entity.php:35 {
      Entity->__toString()
      › {
      ›     return $this->type;
      › }
    }
```

That way, a PHP Fatal error is triggered at save time (because `Entity::__toString()` is called, if this method exists, to get a "representation" of the instance) but I have no way to handle this properly. 
I cannot wrap the `__toString` call in a try/catch as it triggers a fatal error (which is different from an exception) and even if I could handle this at `auditor` level, this method would fail anyway if called from anywhere else.

**Comment by SanderVerkuil** [comment]
@DamienHarper Thanks for taking a look at it. The weird thing though, is that it was initialized, as it must be initialized through the constructor, so it could not be uninitialized. For some reason though, it was actually initialized.

Maybe this is a weird mixture of other dependencies that don't play together very well, as I couldn't reproduce it here either.

When I tried to reproduce it locally in my own project it also worked just fine going through the regular business rules, but it would keep on breaking when creating the entities with DataFixtures. I did manage to fix it by setting the `__toString()` method as follows:

```php
/** @Auditable */
class Test 
{
    private string $type;

    public function __construct(string $type) 
    {
        $this->$type = $type;
    }

    public function __toString()
    {
        # Unfortunately this change is necessary, otherwise the Auditor fails to generate a nice diff. Might be solved with a new auditor update.
        $prop = (new \ReflectionClass(self::class))->getProperty('type');
        $prop->setAccessible(true);
        if (!$prop->isInitialized($this)) {
            return spl_object_hash($this);
        }
        return $this->type;
    }
}
```

And the even weirder behavior was that when setting the property to `''` within the property definition, the property had been initialized to `null`, so I'd get an error somewhere else stating that `null` can't be used as a string value.

I'll try and see if I can dig into it more, and see what dark magic the DataFixture performed, resulting in this weird behavior.

I think it would be solved by wrapping the `(string)` in a `try/catch`, like:
```php
try {
  $representation = (string)$entity;
} catch (\Throwable $t)
{
  // handle the error, maybe like so:
  $representation = spl_object_hash($entity);
}
```

though I'm not so sure about that, and whether this is something that this project should actively do. And in order to correctly verify this, we ought to determine where the error actually comes from.

**Comment by DamienHarper** [comment]
@SanderVerkuil you're right, I can workaround the issue using a try/catch regarding a Throwable instead of an Exception (my bad), will do a PR shortly.

**Comment by DamienHarper** [comment]
@SanderVerkuil feel free to share your findings about `DataFixture`'s dark magic regarding typed properties ;)

**Comment by SanderVerkuil** [comment]
What I think happened, was that I was using the `ReferenceRepository`, which internally fetches only the `reference`.

After a fixture is loaded, the manager is cleared and the other fixtures are being loaded. I tried to recreate it by adding the fixture bundle as a dependency, and using the ORMExecutor with the references, but to no avail.

I think it happens when the DB has an entity `DummyEntity` with an ID of `1`, and instead of fetching that entity fully, the underlying system calls the `$em->getReference(DummyEntity, 1)` which loads the partial entity.

However, I do see that the `initializeObject` method is called, so it _could_ be that the initializer of the object is just wrong :/

Thanks for looking into it though, and wrapping it in a Throwable. It might be worth it to throw a user warning, so we don't completely hide the error that happens?

**Comment by DamienHarper** [comment]
> It might be worth it to throw a user warning, so we don't completely hide the error that happens?

Well, I think it might be ok to add that warning on one hand. But on the other hand I think most users won't find the root cause of the warning or won't be able to fix it if it comes from Doctrine. So they'll get warnings they can't get rid of which can be frustrating.
